#!/bin/bash

# Touch our variables so they are owned by our user
if [ ! -f $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB ]; then
	touch $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB
	# 0 - not initialized, 1 - globgal password defined, 2, initialized
	echo 0 > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB
fi

# Tell everyone the status of INIT-DB
echo "OPENSHIFT_MARIADB_INIT_DB=`cat $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB`"
