#!/bin/bash

set -e

#app_name=$1
#namespace=$2
#local_gear=$3

# echo "$@" >> $OPENSHIFT_MARIADB_DIR/hook-log

echo ${@:4};
for arg in ${@:4}; do
	arg=$(echo "$arg" | tr -d "\n" | tr -d "'")
	gear=$(echo "$arg" | cut -f 1 -d '=')
	addr=$(echo "$arg" | cut -f 3 -d '=')

	# ignore if empty
	if [[ -z "$arg" ]]; then
		continue
	fi

	# addr will have a format like this: 
	# http://haproxyurl:port

	echo $addr > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_HAPROXY_URL

done
