#!/bin/bash

set -e

#app_name=$1
#namespace=$2
#local_gear=$3

# echo "$@" >> $OPENSHIFT_MARIADB_DIR/hook-log

# Touch our variables so they are owned by our user
if [ ! -f $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_HAPROXY_URL ]; then
	touch $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_HAPROXY_URL
fi

echo ${@:4};
for arg in ${@:4}; do
	arg=$(echo "$arg" | tr -d "\n" | tr -d "'")
	gear=$(echo "$arg" | cut -f 1 -d '=')
	addr=$(echo "$arg" | cut -f 3 -d '=')

	# Set passwords to initialized, we upgrade but never downgrade the db-init
	echo $addr > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_HAPROXY_URL

done
