#!/bin/bash

set -e

#app_name=$1
#namespace=$2
#local_gear=$3

echo -n "Set MariaDB Galera Node: "
echo "$@" >> $OPENSHIFT_MARIADB_DIR/hook-log

# find main node addr
echo ${@:4};
for arg in ${@:4}; do
	arg=$(echo "$arg" | tr -d "\n" | tr -d "'")
	gear=$(echo "$arg" | cut -f 1 -d '=')
	addr=$(echo "$arg" | cut -f 3 -d '=')

echo "arg=$arg gear=$gear addr=$addr"

	if fgrep -q "$addr" $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_GALERA_GEARS
	then
		# Remove Existing Gear
		# Assumption that if the same gets published it is because the gear is being removed
		galera_gears=`cat $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_GALERA_GEARS`
		for remove_gear in ${addr} ; do
			galera_gears=${galera_array/ $remove_gear /}
		done
		echo -n $galera_gears > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_GALERA_GEARS

	else
		# Append to list of gears
		echo -n "${addr} " >> $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_GALERA_GEARS
	fi	
done

