#!/bin/bash

set -e

#app_name=$1
#namespace=$2
#local_gear=$3

# echo "$@" >> $OPENSHIFT_MARIADB_DIR/hook-log

echo ${@:4};
for arg in ${@:4}; do
	arg=$(echo "$arg" | tr -d "\n" | tr -d "'")
	gear=$(echo "$arg" | cut -f 1 -d '=')
	addr=$(echo "$arg" | cut -f 3 -d '=')

echo "arg=$arg gear=$gear addr=$addr"

	if fgrep -q "$addr" $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_NODE_GEARS
	then
		# Remove the address from the list
		sed "/${addr}/d" $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_NODE_GEARS

	else
		# Append to list of gears
		echo -e "${addr}\n" >> $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_NODE_GEARS
	fi	
done

