#!/bin/bash

set -e

#app_name=$1
#namespace=$2
#local_gear=$3

# echo "$@" >> $OPENSHIFT_MARIADB_DIR/hook-log

echo ${@:4};
for arg in ${@:4}; do
	arg=$(echo "$arg" | tr -d "\n" | tr -d "'")
	gear=$(echo "$arg" | cut -f 1 -d '=')
	addr=$(echo "$arg" | cut -f 3 -d '=')

	# addr will have a format like this: 
	# 0 or 1

# Only accept the broadcast if passwords are set or cluster intialized already
# Set passwords to initialized, but don't downgrade from initialized cluster
if [ $addr = 1 ] || [ $addr = 2 ] && [ `cat $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB` = 0 ]
then
	echo "1" > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB
fi

